name: iOS Development Build

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-13
        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Setup Expo
              uses: expo/expo-github-action@v8
              with:
                  expo-version: latest
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - uses: maxim-lobanov/setup-xcode@v1
              with:
                   xcode-version: 15.2

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Build iOS app
              run: eas build --profile development --platform ios --local --non-interactive --output ${{ github.workspace }}/app-release.ipa

            - name: Upload IPA artifact
              uses: actions/upload-artifact@v2
              with:
                  name: app-release
                  path: ${{ github.workspace }}/app-release.ipa
