name: Android Development Build

on:
    push:
        branches:
            - dev
            - v2
        paths:
            - package.json
            - app.json
    workflow_dispatch: ~

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Setup Android SDK
              uses: android-actions/setup-android@v3

            - name: Setup Expo
              uses: expo/expo-github-action@v8
              with:
                  expo-version: latest
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Build Android app
              run: eas build --profile development --platform android --local --output ${{ github.workspace }}/app-release.apk

            - name: Upload APK artifact
              uses: actions/upload-artifact@v2
              with:
                  name: app-release
                  path: ${{ github.workspace }}/app-release.apk
